job_titles_dict = {
    'administrative services mgr': 'administrative services manager',
    'airport emerg planning coord': 'airport emergency planning coordinator',
    'airport mechanical maint sprv': 'airport mechanical maintenance supervisor',
    'airport noise abatement spec': 'airport noise abatement specialist',
    'airport property specialist 1': 'airport property specialist i',
    'airport communications supervisor': 'airports communications supervisor',
    'animal care assistant supervisor': 'animal care assistant supervisor',
    'apprentice stationary engineer, sewage plant': 'apprentice stationary engineer, sewage plant',
    'apprentice stationary engineer,water treatment pln': 'apprentice stationary engineer, water treatment plant',
    'architectural assistant  i': 'architectural assistant 1',
    'architectural assistant 2': 'architectural assistant ii',
    'architectural associate  i': 'architectural associate 1',
    'architectural associate 2': 'architectural associate ii',
    'area sprv parks, squares & fac': 'area supervisor, parks, squares and facilities',
    'asphalt finisher supervisor 1': 'asphalt finisher supervisor i',
    'asphalt plant supervisor 1': 'asphalt plant supervisor i',
    'assistant chief attorney 1': 'assistant chief attorney i',
    'assistant chief attorney 2': 'assistant chief attorney ii',
    'sst chf dist atty\'s invstgtor': 'assistant chief district attorney\'s investigator',
    'asst chf of dept (fire dept)': 'assistant chief of department, (fire department)',
    'asst chf prob ofc, juv prob': 'assistant chief probation officer-juvenile probation',
    'asst chf victim/wit invstgtor': 'assistant chief victim/witness investigator',
    'asst chf, bur clm invest&admin': 'assistant chief, bureau of claims investigation & administration',
    'asst clk, board of supervisors': 'assistant clerk, board of supervisors',
    'assistant deputy chief 2': 'assistant deputy chief ii',
    'asst.dep.dir., port': 'assistant deputy director, port',
    'asst dir clinical svcs 2': 'assistant director of clinical services ii',
    'assistant director of clinical services i': 'assistant director of clinical services 1',
    'asst dir, log cabin rnch': 'assistant director, log cabin ranch',
    'asst director, juvenile hall': 'assistant director, juvenile hall',
    'asst electronic main tech': 'assistant electronic maintenance technician',
    'asst engr': 'assistant engineer',
    'asst forensic toxicologist 1': 'assistant forensic toxicologist i',
    'asst general services manager': 'assistant general services manager',
    'asst materials coordinator': 'assistant materials coordinator',
    'asst med examiner': 'assistant medical examiner',
    'asst superintendent rec': 'assistant superintendent recreation',
    'automotive body & fender wrk': 'automotive body and fender worker',
    'automotive body and fender worker supervisor i': 'auto body & fender wrk sprv 1',
    'automotive machinist sprv 1': 'automotive machinist supervisor i',
    'automotive mechanic assistant supervisor': 'automotive mechanic asst sprv',
    'automotive mechanic sprv 1': 'automotive mechanic supervisor i',
    'automotive transit shop supervisor i': 'automotive trnst shop sprv 1',
    'assoc engineer': 'associate engineer',
    'captain, emergency med svcs': 'captain, emergencycy medical services',
    'carpenter supervisor 1': 'carpenter supervisor 2',
    'carpenter supervisor i': 'carpenter supervisor ii',
    'cashier 1': 'cashier 2',
    'cashier i': 'cashier ii',
    'cement finisher supervisor 1': 'cement finisher supervisor 2',
    'cement finisher supervisor i': 'cement finisher supervisor ii',
    'central processing & dist tech': 'central processing and distribution technician',
    'chief attorney i (civil & criminal)': 'chief attorney 1 (civil & criminal)',
    'chief dep adlt prob of (sfers)': 'chief deputy adult probation officer',
    'chief deputy adlt probation of': 'chief deputy adult probation officer',
    'chief district attorney\'s investigator': 'chief district attorney\'s investigator',
    'chief payroll and personnel clerk': 'chief payroll & personnel clerk',
    'chief, fire department': 'chief of department, (fire department)',
    'city shops assistant superintendent': 'city shops asst superintendent',
    'communication line sprv1': 'communication line supervisor i',
    'communications dispatcher 1': 'communications dispatcher 2',
    'communications dispatcher i': 'communications dispatcher ii',
    'communications line worker supervisor ii': 'communications line wrk sprv 2',
    'communications systems tech': 'communications systems technician',
    'community development assistant': 'community development asst',
    'community development spec': 'community development specialist',
    'conservatorship/case mgnt supv': 'conservatorship/case mgt sprv',
    'contract compliance officer 1': 'contract compliance officer 2',
    'contract compliance officer i': 'contract compliance officer ii',
    'coordinator, human rights commission': 'coord, human rights comm',
    'counselor, family court service': 'counselor, family court svc',
    'court alternative specialist 1': 'court alternative specialist i',
    'court assistant - senior, superior court': 'court asst-sr, superior court',
    'court assistant, superior court': 'court asst., superior court',
    'ourt computer sys manager': 'court computer systems manager',
    'crime lab mgr': 'crime laboratory manager',
    'criminal justice specialist 2': 'criminal justice specialist ii',
    'curator 1': 'curator i',
    'curator 2': 'curator ii',
    'curator 3': 'curator iii',
    'curator 4': 'curator iv',
    'customer service agent supervisor': 'customer service agent supv',
    'department head i': 'dept head i',
    'department head ii': 'dept head ii',
    'department head iii': 'dept head iii',
    'department head iv': 'dept head iv',
    'department head v': 'dept head v',
    'eputy dir i, mta': 'deputy director i - municipal transportation age',
    'deputy dir ii, mta': 'deputy director ii - municipal transportation ag',
    'district attorney\'s investigator': 'district attry\'s investigator',
    'div director, adult probation': 'division director adult probation',
    'electric motor repair sprv 1': 'electric motor repair supervisor i',
    'electrical trnst shop sprv 1': 'electrical transit shop sprv 1',
    'electrical trnst mech sprv 1': 'electrical transit mechanic supervisor i',
    'electrical transit system mech': 'electrical transit system mechanic',
    'electrician supervisor 1': 'electrician supervisor i',
    'electrician supervisor 2': 'electrician supervisor ii',
    'electroencephalograph tech 1': 'electroencephalograph technician i',
    'electronic maintenance tech': 'electronic maintenance technician',
    'emergency med svcs agency spec': 'emergency medical services agency specialist',
    'employee relations representat': 'employee relations representative',
    'engineering associate 2': 'engineering associate ii',
    'epidemiologist 1': 'epidemiologist 2',
    'epidemiologist i': 'epidemiologist ii',
    'executive secretary 1': 'executive secretary i',
    'executive secretary 2': 'executive secretary ii',
    'executive secretary 3': 'executive secretary iii',
    'field services assistant supervisor': 'field svcs asst supv',
    'fingerprint technician 1': 'fingerprint technician i',
    'fingerprint technician 2': 'fingerprint technician ii',
    'fingerprint technician 3': 'fingerprint technician iii',
    'fire safety inspector 2': 'fire safety inspector ii',
    'food service manager administrator': 'food service mgr administrator',
    'general laborer supervisor 1': 'general laborer supervisor i',
    'glazier supervisor 1': 'glazier supervisor i',
    'government and public affairs manager': 'govrnmt/publ affairs mgr',
    'health care billing clerk 1': 'health care billing clerk i',
    'health care billing clerk 2': 'health care billing clerk ii',
    'health program coordinator 1': 'health program coordinator i',
    'health program coordinator 2': 'health program coordinator ii',
    'health program coordinator 3': 'health program coordinator iii',
    'health worker 1': 'health worker i',
    'health worker 2': 'health worker ii',
    'health worker 3': 'health worker iii',
    'health worker 4': 'health worker iv',
    'heating and ventilating inspector': 'heating/ventilating inspector',
    'heavy equipment operations assistant supervisor': 'heavy equip ops asst sprv',
    'heavy equipment operations supervisor': 'heavy equipment ops sprv',
    'hospital eligibility worker supervisor': 'hospital elig wrk supervisor',
    'hospital eligibility worker': 'hospital eligiblity worker',
    'housekeeper/food service cleaner': 'housekeeper/food service clnr',
    'inspector, weights & measures': 'inspector of weights and measures',
    'investigator, taxi & access svcs': 'investigator, taxi & accesssvcs',
    'is administrator 1': 'is administrator i',
    'is administrator 2': 'is administrator ii',
    'is administrator 3': 'is administrator iii',
    'is business analyst-assistant': 'is business analyst - assistant',
    'is business analyst-senior': 'is business analyst - senior',
    'is business analyst-principal': 'is business analyst - principal',
    'is engineer-assistant': 'is engineer - assistant',
    'is engineer-journey': 'is engineer - journey',
    'koiis engineer-principal': 'is engineer - principal',
    'is engineer-senior': 'is engineer - senior',
    'is operator-analyst': 'is operator - analyst',
    'is operator-journey': 'is operator - journey',
    'is operator-senior': 'is operator - senior',
    'is prg analyst-principal': 'is programmer analyst - principal',
    'is program analyst-assistant': 'is programmer analyst - assistant',
    'is program analyst-senior': 'is programmer analyst - senior',
    'is technician - journey': 'is technical-journey',
    'is technician assistant': 'is technician - assistant',
    'is technician-supervisor': 'is technician - supervisor',
    'is technician-senior': 'is technician - senior',
    'is trainer-assistant': 'is trainer - assistant',
    'is trainer-journey': 'is trainer - journey',
    'is trainer-senior': 'is trainer - senior',
    'janitorial services assistant supervisor': 'janitorial svcs asst sprv',
    'laboratory services manager': 'lab svcs mgr',
    'landscape architectural associate i': 'landscape architect assoc 1',
    'landscape architectural associate ii': 'landscape architect assoc 2',
    'legal secretary 1': 'legal secretary i',
    'legal secretary 2': 'legal secretary ii',
    'legislative assistant, city attorney\'s office': 'legislative asst city atty ofc',
    'librarian 1': 'librarian i',
    'librarian 2': 'librarian ii',
    'librarian 2 - asian arts': 'librarian ii - asian arts',
    'librarian 3': 'librarian iii',
    'library technical assistant 1': 'library technical assistant i',
    'library technical assistant 2': 'library technical assistant ii',
    'locksmith supervisor 1': 'locksmith supervisor i',
    'mail and reproduction service supervisor': 'mail & reproduction svc sprv',
    'maintenance machinist assistant supervisor': 'main machinist asst sprv',
    'maintenance machinist supervisor i': 'maintenance machinist sprv 1',
    'manager ii - municipal transportation agency': 'manager ii, mta',
    'manager iii - municipal transportation agency': 'manager iii, mta',
    'manager iv - municipal transportation agency': 'manager iv, mta',
    'manager v - municipal transportation agency': 'manager v, mta',
    'manager vi - municipal transportation agency': 'manager vi, mta',
    'manager vii - municipal transportation agency': 'manager vii, mta',
    'manager viii - municipal transportation agency': 'manager viii, mta',
    'manager,employee relations div': 'manager, employee relations div',
    'maritime marketing representative': 'maritime marketing repr',
    'market research specialists, port': 'market research spec, port',
    'marriage, family & child cnslr': 'marriage, family & child counselor (mfcc)',
    'mechanical shop and equipment superintendent': 'mech shop & equip supt',
    'media production supervisor': 'media production supv',
    'media production technician': 'media production tech',
    'media programming specialist': 'media programming spec',
    'media/security sys spec': 'media/security systems specialist',
    'media/security systems supervisor': 'media/security syst supv',
    'medical records technician supervisor': 'medical records tech sprv',
    'mental health treatment specialist': 'mental hlth treatment spec',
    'ornamental iron worker supervisor i': 'ornamental iron wrk sprv 1',
    'orthopedic technician 1': 'orthopedic technician i',
    'orthopedic technician 2': 'orthopedic technician ii',
    'painter supervisor 1': 'painter supervisor i',
    'painter supervisor 2': 'painter supervisor ii',
    'parking enforcement administrator': 'parking enforcement admin',
    "parking meter repairer supervisor i": "parking meter repairer sprv 1",
    "patient accounts assistant supervisor": "patient accounts asst sprv",
    "patient services finance technician": "patient svcs finance tech",
    "piledriver supervisor 1": "piledriver supervisor i",
    "planner 1": "planner i",
    "planner 2": "planner ii",
    "planner 3": "planner iii",
    "planner 3-environmental review": "planner iii-environmental review",
    "planner 4": "planner iv",
    "planner 4-environmental review": "planner iv-environmental review",
    "planner 5": "planner v",
    "plumber supervisor 1": "plumber supervisor i",
    "plumber supervisor 2": "plumber supervisor ii",
    "police officer 2": "police officer ii",
    "police officer 3": "police officer iii",
    "porter supervisor 1": "porter supervisor i",
    "power generation technician 1": "power generation technician i",
    "power generation technician 2": "power generation technician ii",
    "power plant supervisor 1": "power plant supervisor i",
    "principal environmental specialist": "principal environ specialist",
    "principal management analyst": "principal mgmt analyst",
    "principal real property officer": "principal real property ofc",
    "principal recreation supervisor": "principal recreation sprv",
    "project manager 1": "project manager i",
    "project manager 2": "project manager ii",
    "project manager 3": "project manager iii",
    "project manager 4": "project manager iv",
    "public relations manager": "public relations mgr",
    "public safety communications technician": "public safety comm tech",
    "public safety communications dispatcher": "public safetycomm disp",
    "public service aide-admin": "public service aide-administrative",
    "radiologic tech sprv": "radiologic technologist supervisor",
    "rehabilitation services coordinator": "rehabilitation svcs coord",
    "roofer supervisor 1": "roofer supervisor i",
    "secretary 1": "secretary i",
    "secretary 2": "secretary ii",
    "secretary, comm on the environ": "secretary, commission on the environment",
    "senior const inspector": "senior construction inspector",
    "senior electrical inpsector": "senior electrical inspector",
    "sewage treatment plant superintendent": "sewage treatment plant supt",
    "sheet metal supervisor 1": "sheet metal supervisor i",
    "sheet metal worker supervisor ii": "sheet metal wrk supervisor 2",
    "shelter office assistant supervisor": "shelter office asst supv",
    "shelter office supervisor": "shelter officer supervisor",
    "shelter service rep": "shelter service representative",
    "special assistant 3": "special assistant iii",
    "special assistant 14": "special assistant xiv",
    "special assistant 15": "special assistant xv",
    "special assistant 16": "special assistant xvi",
    "special assistant 18": "special assistant xviii",
    "special assistant xxii": "special assistant 22",
    "specialist in aging 2": "specialist in aging ii",
    "station agent, muni railway": "station agent, municipal railway",
    "street repair supervisor 2": "street repair supervisor ii",
    "supervising physician spec": "supervising physician specialist",
    "supply room attendant": "supply room attendent",
    "survey assistnat i": "survey assistant i",
    "swimming instructor/pool lifeguard": "swimming instr/pool lifeguard",
    "telecommunications tech supv": "telecommunications technician supervisor",
    "track maintenance superintendent,municipal railway": "track maint supt, muni railway",
    "track maintenance worker supervisor i": "track maint wrk sprv 1",
    "transit manager 1": "transit manager i",
    "transit manager 2": "transit manager ii",
    "transit paint shop sprv1": "transit paint shop supervisor i",
    "transit planner 2": "transit planner ii",
    "transit planner 4": "transit planner iv",
    "transit power line sprv1": "transit power line supervisor i",
    "transmission line supervisor 1": "transmission line supervisor i",
    "utility plumber supervisor 1": "utility plumber supervisor i",
    "utility plumber supervisor 2": "utility plumber supervisor ii",
    "vet laboratory technologist": "veterniary laboratory technologist",
    "victim/witness investigator 1": "victim/witness investigator i",
    "victim/witness investigator 2": "victim/witness investigator ii",
    "victim/witness investigator 3": "victim/witness investigator iii",
    "volunteer/outreach coord": "volunteer/outreach coordinator",
    "water & power maint sprv 1": "water and power maintenance supervisor i",
    "water conservation admin": "water conservation administrator",
    "water const&main supt": "water construction and maintenance superintendent",
    "water quality tech iii": "water quality technician iii",
    "water quality technician i/ii": "water qualitytech i/ii",
    "wharfinger 1": "wharfinger i",
    "wharfinger 2": "wharfinger ii",
    "wire rope cable maint sprv": "wire rope cable maintenance supervisor",
    "wire rope cable maintenance mechanic": "wire rope cable maint mechanic",
    "worker's compensation supervisor i": "worker's comp supervisor 1"
}